replicaCount: 2

deployment:
  namespace: ill-web

image:
  repository: illustriousonline/ill-web
  tag: 0.0.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: illustrious.online
  path: /
  pathType: Prefix
  tlsSecretName: web-tls

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
