name: "[ill.web] Execute checks & tests"
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  web-check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
        with:
          bun-version: latest
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Run Biome Checks
        run: bun run check
      - name: Run unit tests
        run: bun run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: illustrious-web
          files: ./coverage/lcov-report/index-lcov.html
          slug: Illustrious-Online/illustrious.web
      - name: Run vitest with junit output
        run: bun run test:junit
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: illustrious-web
          slug: Illustrious-Online/illustrious.web
